### ISSUE TITLE
Doesn't seem to do anything?

### ISSUE THREAD

**Issue by tommed** [BrunoSalerno/mapbox-gl-draw-cut-line-mode#4]
I have followed your example in the README, but all I get when I switch to the `cut_line` is a cross hair which has no impact on anything I select. Double-clicking still zooms and single clicking has no impact.

I think a working demo (as mentioned in the other comment) would allow us to see how you envisaged this to actually work.. as I'm assuming I've misunderstood what this is meant to do.

**Comment by usb248** [comment]
This mode is so buggy. Detection features under cross hait is hazardous....

**Comment by BrunoSalerno** [comment]
@tommed sorry you are experiencing this bug. Can you create a jsfiddle (or equivalent) so I can debug it?

**Comment by tommed** [comment]
> @tommed sorry you are experiencing this bug. Can you create a jsfiddle (or equivalent) so I can debug it?

I’m not sure you need me to. Just try using it and i think you’ll find what we’re talking about 😕

**Comment by BrunoSalerno** [comment]
@tommed all right, sorry for that. I'll try to debug it in the upcoming days.

**Comment by BrunoSalerno** [comment]
@tommed one extra question: what version of Mapbox GL JS and Mapbox GL Draw were you using?

**Comment by tommed** [comment]
Latest and greatest at the time of raising; double-circled this before raising. Again, sorry but don’t have the code anymore to get exact version number.

**Comment by BrunoSalerno** [comment]
@tommed I added an example in the example/ folder, and I can't reproduce the bug. The only minor fix that I added is that now the cursor is restored to `inherit` after the split is performed. If you find time to check the example and you encounter the problem again, please, feel free to reopen the issue.
